import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "@/store/features/User/UserContext";
import { FeedbackContextProvider } from "@/store/features/Feedback/FeedbackContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <FeedbackContextProvider>
            {children}
          </FeedbackContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
