import type { Metadata } from "next";
import DashboardNav from "@/components/widget/DasboardNav";
import Sidebar from "@/components/widget/Sidebar";


export const metadata: Metadata = {
    title: "Feedback Share - Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <main className='bg-[#EBEBEB] flex relative'>
                    <div className='bg-white fixed top-0 left-0 h-screen'>
                        <Sidebar />
                    </div>
                    <div className='relative pl-[330px] w-full'>

                        <DashboardNav />
                        {children}
                    </div>                    
                </main>
            </body>
        </html>
    );
}
