import type { Metadata } from "next";
import DashboardNav from "@/components/widget/DasboardNav";
import Sidebar from "@/components/widget/Sidebar";


export const metadata: Metadata = {
    title: "Feedback Share - Dashboard",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <main className='bg-[#EBEBEB] flex relative'>
            <div className='bg-white z-30 fixed top-0 left-0 h-screen'>
                <Sidebar />
            </div>
            <div className='relative pl-[330px] w-full'>

                <DashboardNav />
                {children}

                <footer className="bg-white">
                    <p className="text-center text-sm pt-2 pb-4">&copy; 2024 | Israel Chidera</p>
                </footer>
            </div>


        </main>
    );
}
